# -*- coding: utf-8 -*-
"""logiroute-rs-fleet-analytics_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iGKvf6Ns7atKXHd6_MTTsjcqD_ZGiMG
"""

# !pip install h3 pandas

import os
import pandas as pd
import h3

# Definição do diretório - Pasta atual onde o notebook está rodando
base_path = './'

# Carregamento dos datasets brutos
orders = pd.read_csv(os.path.join(base_path, 'olist_orders_dataset.csv'))
items = pd.read_csv(os.path.join(base_path, 'olist_order_items_dataset.csv'))
customers = pd.read_csv(os.path.join(base_path, 'olist_customers_dataset.csv'))
geolocation = pd.read_csv(os.path.join(base_path, 'olist_geolocation_dataset.csv'))

# Filtragem de clientes no Rio Grande do Sul
customers['customer_state'] = customers['customer_state'].astype(str).str.upper().str.strip()
customers['customer_zip_code_prefix'] = pd.to_numeric(customers['customer_zip_code_prefix'], errors='coerce')

is_rs_state = customers['customer_state'] == 'RS'
is_rs_cep = (customers['customer_zip_code_prefix'] >= 90000) & (customers['customer_zip_code_prefix'] <= 99999)
customers_rs = customers[is_rs_state | is_rs_cep].copy()

# Junção de pedidos e consolidação de valores por pedido
df_rs = orders.merge(customers_rs, on='customer_id', how='inner')

items_agg = items.groupby('order_id').agg({
    'freight_value': 'sum',
    'price': 'sum'
}).reset_index()

df_rs = df_rs.merge(items_agg, on='order_id', how='inner')

# Filtragem e agregação geográfica por CEP
geolocation['geolocation_zip_code_prefix'] = pd.to_numeric(geolocation['geolocation_zip_code_prefix'], errors='coerce')

geo_valid = geolocation[
    (geolocation['geolocation_lat'] >= -34.0) & (geolocation['geolocation_lat'] <= -26.0) &
    (geolocation['geolocation_lng'] >= -58.0) & (geolocation['geolocation_lng'] <= -49.0)
].copy()

geo_agg = geo_valid.groupby('geolocation_zip_code_prefix').agg({
    'geolocation_lat': 'mean',
    'geolocation_lng': 'mean'
}).reset_index()

df_rs = df_rs.merge(
    geo_agg,
    left_on='customer_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='inner'
)

# Cálculo de métricas temporais e indicadores de atraso
df_rs['order_delivered_customer_date'] = pd.to_datetime(df_rs['order_delivered_customer_date'])
df_rs['order_estimated_delivery_date'] = pd.to_datetime(df_rs['order_estimated_delivery_date'])
df_rs['order_purchase_timestamp'] = pd.to_datetime(df_rs['order_purchase_timestamp'])

df_rs['atraso_dias'] = (df_rs['order_delivered_customer_date'] - df_rs['order_estimated_delivery_date']).dt.total_seconds() / 86400
df_rs['tempo_entrega_dias'] = (df_rs['order_delivered_customer_date'] - df_rs['order_purchase_timestamp']).dt.total_seconds() / 86400
df_rs['is_atrasado'] = (df_rs['atraso_dias'] > 0).astype(int)

# Indexação espacial H3 (Resolução 7)
df_rs['h3_index'] = [h3.latlng_to_cell(lat, lng, 7) for lat, lng in zip(df_rs['geolocation_lat'], df_rs['geolocation_lng'])]

# Coordenadas do centroide de cada célula H3
coords = [h3.cell_to_latlng(cell) for cell in df_rs['h3_index']]
df_rs['h3_lat'] = [c[0] for c in coords]
df_rs['h3_lng'] = [c[1] for c in coords]

# Agregação final por hexágono H3
h3_summary = df_rs.groupby('h3_index').agg(
    total_pedidos=('order_id', 'count'),
    media_atraso_dias=('atraso_dias', 'mean'),
    media_tempo_entrega=('tempo_entrega_dias', 'mean'),
    taxa_atraso=('is_atrasado', 'mean'),
    faturamento_total=('price', 'sum'),
    frete_medio=('freight_value', 'mean'),
    lat=('h3_lat', 'first'),
    lng=('h3_lng', 'first')
).reset_index()

h3_summary['taxa_atraso_pct'] = h3_summary['taxa_atraso'] * 100

# Exportação do dataset tratado no diretório atual
output_file = os.path.join(base_path, 'logiroute_rs_h3_summary.csv')
h3_summary.to_csv(output_file, index=False, decimal=',', encoding='utf-8-sig')

# Logs de execução
print(f"Processamento concluído. Arquivo salvo em: {output_file}")
print(f"Total de células H3 mapeadas: {len(h3_summary)}")

# Visualização das primeiras linhas do output
h3_summary.head()